server:
  port: 80

spring:
  application:
    name: two
  profiles:
    active: dev
  resources:
    add-mappings: false
    static-locations: classpath:/static/,classpath:/templates/index/
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
#配置日志这里日志用xml去配置
logback:
  dir: ./log

mybatis:
  #为实体对象所在的包，跟数据库表一一对应
  #  type-aliases-package: com.arc.model.common
  #mapper文件的位置
  mapper-locations: classpath:mapper/*/*.xml

# 自定义参数；说明 1、web.system.initial:是否在系统启动的时候初始化一些操作
web:
  upload:
    file:
  system:
    initial: true
#  key: ZZ

########################################################
#          不同环境         Environment for Localhost  注意：数据配置在这里
########################################################
---
spring:
  servlet:
    multipart:
      max-file-size: 10200MB
      max-request-size: 102400MB
  profiles: dev
  datasource:
    #爆红不要紧张，没有问题的只是编辑工具不能识别造成的，本身是正确的
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test2?useUnicode=true&characterEncoding=UTF-8&useAffectedRows=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: admin
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 15
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 1
